<script setup>
import{nextTick,onBeforeUnmount,onMounted,ref,watch}from'vue';import BreathingExercise from'./BreathingExercise.vue';import GuidedMovement from'./GuidedMovement.vue';import{loadWriting,saveWriting}from'../utils/storage';import{createAmbientAudio}from'../utils/audio.js'
const props=defineProps({targetSection:{type:String,default:''}}),emit=defineEmits(['target-reached','completed']);const sounds=['雨声','海浪','森林','咖啡馆','轻钢琴'],playing=ref(''),volume=ref(22),audioError=ref(''),highlighted=ref('');let highlightTimer;const audio=createAmbientAudio(v=>playing.value=v)
async function toggleSound(sound){audioError.value='';try{await audio.play(sound)}catch{audioError.value='当前浏览器暂时无法播放声音，请检查声音权限后重试。'}}watch(volume,v=>audio.setVolume(v/100))
const movements=[
{id:'stretch',name:'2 分钟伸展',startLabel:'开始 2 分钟伸展',icon:'↟',duration:'跟着六个动作慢慢伸展',phases:[['放松肩膀','让双肩自然下沉',20],['缓慢转动肩颈','动作小一点，不要勉强',20],['双臂向上伸展','手臂向上，保持自然呼吸',20],['身体左右侧弯','缓慢换边，感受身体侧面',20],['放松腿部','轻轻活动膝盖和脚踝',20],['深呼吸并站稳','慢慢站稳，做一次深呼吸',20]]},
{id:'walk',name:'10 分钟散步',startLabel:'开始散步',icon:'↝',duration:'不看步数，只留意脚步',phases:[['先走起来','不用想什么，只注意脚步和呼吸',120],['看看周围','留意三个之前没注意到的东西',180],['保持舒服的步伐','不需要走得快，让身体自然移动',180],['慢慢收尾','看看身体和刚才相比有没有一点变化',120]]},
{id:'light',name:'15 分钟轻运动',startLabel:'开始轻运动',icon:'⌁',duration:'温和活动，不追求强度',phases:[['原地热身','轻轻踏步，让身体暖起来',180],['下肢活动','做几次缓慢深蹲或坐站练习',240],['上肢伸展','活动手臂、肩膀和背部',240],['自由活动','选择让身体舒服的动作',180],['慢慢收尾','放慢速度，调整呼吸',60]]}
].map(item=>({...item,phases:item.phases.map(([title,tip,seconds])=>({title,tip,seconds}))}));const selectedMovement=ref(null)
const prompts=['如果这件事发生在你的朋友身上，你会怎么安慰他？','今天有哪些事情虽然很小，但你已经处理好了？','现在最让你担心的是什么？其中哪些部分是你能控制的？'],promptIndex=ref(Math.floor(Math.random()*prompts.length)),writing=ref(loadWriting());watch(writing,v=>saveWriting(v));function nextPrompt(){promptIndex.value=(promptIndex.value+1)%prompts.length}
async function locate(section){if(!section)return;await nextTick();requestAnimationFrame(()=>{const el=document.getElementById(section);if(!el)return;el.scrollIntoView({behavior:'smooth',block:innerWidth<760?'start':'center'});highlighted.value=section;clearTimeout(highlightTimer);highlightTimer=setTimeout(()=>highlighted.value='',1800);emit('target-reached')})}onMounted(()=>locate(props.targetSection));watch(()=>props.targetSection,locate);onBeforeUnmount(()=>{clearTimeout(highlightTimer);audio.destroy()})
function complete(item){emit('completed',item)}
</script>
<template><section class="care-view"><div class="section-intro"><p class="eyebrow">自我关怀空间</p><h1>把一点温柔，<span>留给此刻的自己</span></h1><p>不用完成所有练习，选择一个当下愿意尝试的就好。</p></div>
<section id="care-breathing" :class="['card','breathing-card','care-target',{'care-highlight':highlighted==='care-breathing'}]"><div class="care-title"><div><span>01</span><div><h2>呼吸一下</h2><p>让身体先慢下来一点。</p></div></div></div><BreathingExercise @complete="complete"/></section>
<section id="care-sound" :class="['care-section','care-target',{'care-highlight':highlighted==='care-sound'}]"><div class="section-heading"><div><p class="eyebrow">02 · 听点声音</p><h2>给注意力一个暂时停靠的地方</h2></div><p v-if="playing" class="playing-status"><i></i>正在播放：{{playing}}</p><p v-else>选择一种舒服的声音</p></div><div class="sound-grid"><button v-for="sound in sounds" :key="sound" :class="{active:playing===sound}" type="button" @click="toggleSound(sound)"><span>{{sound==='雨声'?'♩':sound==='海浪'?'≈':sound==='森林'?'♧':sound==='咖啡馆'?'☕':'♫'}}</span><strong>{{sound}}</strong><small>{{playing===sound?'点击暂停':'播放声音'}}</small></button></div><div class="volume-row"><label for="ambient-volume">音量</label><input id="ambient-volume" v-model.number="volume" type="range" min="0" max="60" :style="{'--value':`${volume/60*100}%`}"><span>{{volume}}%</span></div><p v-if="audioError" class="audio-error">{{audioError}}</p><div class="care-finish-row"><p>听一会儿就好，不需要计时。</p><button class="care-done-button" type="button" :disabled="!playing" @click="complete({actionId:'sound',actionName:`环境音 · ${playing}`})">我听好了</button></div></section>
<section id="care-movement" :class="['care-section','care-target',{'care-highlight':highlighted==='care-movement'}]"><div class="section-heading"><div><p class="eyebrow">03 · 动一动</p><h2>身体活动一点，情绪也可能松一点</h2></div><p>选一个，跟着节奏慢慢做</p></div><div class="movement-picker"><button v-for="item in movements" :key="item.id" :class="{active:selectedMovement?.id===item.id}" @click="selectedMovement=item"><span>{{item.icon}}</span><strong>{{item.name}}</strong><small>{{item.duration}}</small></button></div><GuidedMovement v-if="selectedMovement" :key="selectedMovement.id" :action="selectedMovement" @complete="complete"/></section>
<section id="care-writing" :class="['writing-card','care-target',{'care-highlight':highlighted==='care-writing'}]"><div class="writing-copy"><p class="eyebrow">04 · 写下来</p><h2>有些感受，写出来会更容易看清。</h2><p class="writing-question">{{prompts[promptIndex]}}</p><button class="text-button" type="button" @click="nextPrompt">换一个问题 ↻</button></div><div><textarea v-model="writing" maxlength="800" placeholder="不用组织语言，想到什么就写什么……"></textarea><div class="text-count">已自动保存在当前设备 · {{writing.length}}/800</div><button class="care-done-button writing-done" type="button" :disabled="!writing.trim()" @click="complete({actionId:'writing',actionName:'自我关怀书写'})">我写好了</button></div></section>
</section></template>
