<script setup>
import{ref}from'vue'
const props=defineProps({modelValue:{type:Array,default:()=>[]},options:{type:Array,required:true},customOptions:{type:Array,default:()=>[]},max:{type:Number,default:Infinity},single:Boolean,placeholder:{type:String,default:'输入标签'}})
const emit=defineEmits(['update:modelValue','add-custom','delete-custom']);const adding=ref(false),text=ref(''),error=ref('')
function toggle(item){if(props.single)return emit('update:modelValue',props.modelValue.includes(item)?[]:[item]);if(props.modelValue.includes(item))emit('update:modelValue',props.modelValue.filter(v=>v!==item));else if(props.modelValue.length<props.max)emit('update:modelValue',[...props.modelValue,item])}
function add(){const value=text.value.trim().slice(0,16);if(!value){error.value='写点内容再添加';return}if([...props.options,...props.customOptions].includes(value)){error.value='这个标签已经有了';return}emit('add-custom',value);emit('update:modelValue',props.single?[value]:[...props.modelValue,value].slice(0,props.max));text.value='';error.value='';adding.value=false}
function remove(item,event){event.stopPropagation();emit('delete-custom',item);if(props.modelValue.includes(item))emit('update:modelValue',props.modelValue.filter(v=>v!==item))}
</script>
<template><div><div class="tag-list"><button v-for="item in [...options,...customOptions]" :key="item" type="button" :class="['tag-chip',{selected:modelValue.includes(item),disabled:!modelValue.includes(item)&&modelValue.length>=max,custom:customOptions.includes(item)}]" :aria-pressed="modelValue.includes(item)" @click="toggle(item)"><span v-if="modelValue.includes(item)">✓</span>{{item}}<span v-if="customOptions.includes(item)" class="tag-remove" aria-label="删除自定义标签" @click="remove(item,$event)">×</span></button><button v-if="!adding" type="button" class="tag-add" @click="adding=true">＋ 添加</button></div><div v-if="adding" class="tag-input-row"><input v-model="text" :placeholder="placeholder" maxlength="16" autofocus @keyup.enter="add" @keyup.esc="adding=false"><button type="button" @click="add">确认</button><button type="button" @click="adding=false;text='';error=''">取消</button></div><p v-if="error" class="tag-error">{{error}}</p></div></template>
