<script setup>
import * as echarts from 'echarts/core'
import {LineChart} from 'echarts/charts'
import {GridComponent,TooltipComponent} from 'echarts/components'
import {CanvasRenderer} from 'echarts/renderers'
import {nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'
echarts.use([LineChart,GridComponent,TooltipComponent,CanvasRenderer])
const props=defineProps({points:{type:Array,required:true},scale:{type:String,required:true},movingAverage:{type:Array,default:()=>[]}})
const chartEl=ref(null);let chart
function axisFormatter(value,index){if(props.scale==='30d'){const last=props.points.length-1;return index===0||index===last||index%5===0?value:''}if(props.scale==='90d')return index%2===0||index===props.points.length-1?value:'';return value}
function tooltipFormatter(params){const data=params.find(item=>item.seriesName==='状态记录')?.data;if(!data||!Number.isFinite(data.value))return'';const range=data.min===data.max?`${data.min}`:`${data.min} - ${data.max}`;return `<div class="chart-tooltip"><strong>${data.detailLabel}</strong><span>平均状态：${data.value}</span><span>记录 ${data.count} 次</span><span>范围：${range}</span></div>`}
function render(){if(!chartEl.value)return;chart||=echarts.init(chartEl.value);const series=[{name:'状态记录',type:'line',data:props.points.map(point=>({...point,value:point.value})),connectNulls:false,smooth:props.scale!=='today',symbol:'circle',showSymbol:true,symbolSize:8,lineStyle:{width:3,color:'#8068c9'},itemStyle:{color:'#fff',borderColor:'#8068c9',borderWidth:3},areaStyle:{color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:'rgba(128,104,201,.13)'},{offset:1,color:'rgba(128,104,201,0)'}])}}];if(props.scale==='30d')series.push({name:'7 日移动平均',type:'line',data:props.movingAverage,lineStyle:{width:2,type:'dashed',color:'#74a087'},itemStyle:{color:'#74a087'},symbol:'none',connectNulls:true,smooth:true});chart.setOption({animationDurationUpdate:280,animationEasingUpdate:'cubicOut',grid:{left:38,right:14,top:24,bottom:props.scale==='7d'?46:36},tooltip:{trigger:'axis',confine:true,appendToBody:false,backgroundColor:'#41394b',borderWidth:0,padding:[9,11],textStyle:{color:'#fff',fontSize:12},formatter:tooltipFormatter},xAxis:{type:'category',boundaryGap:props.scale==='today',data:props.points.map(point=>point.label),axisLine:{lineStyle:{color:'#e9e3eb'}},axisTick:{show:false},axisLabel:{color:'#827a89',fontSize:11,margin:12,hideOverlap:true,lineHeight:15,formatter:axisFormatter}},yAxis:{type:'value',min:0,max:10,interval:2,name:'状态',nameTextStyle:{color:'#aaa2ad',fontSize:11,padding:[0,0,0,-24]},axisLabel:{color:'#aaa2ad',fontSize:11},splitLine:{lineStyle:{color:'#f0ecf1'}}},series},true)}
function resize(){chart?.resize()}onMounted(()=>{nextTick(render);window.addEventListener('resize',resize)});watch(()=>[props.points,props.scale,props.movingAverage],()=>nextTick(render),{deep:true});onBeforeUnmount(()=>{window.removeEventListener('resize',resize);chart?.dispose()})
</script>
<template><div ref="chartEl" class="chart" role="img" :aria-label="`${scale} 情绪状态趋势图`"></div></template>
