<script setup>
import { computed } from 'vue';import TrendChart from './TrendChart.vue';import HistoryList from './HistoryList.vue';import { dayKey,lastSevenDays,mostCommon,recentRecords,weeklyObservation } from '../utils/trend'
const props=defineProps({records:{type:Array,default:()=>[]}});const emit=defineEmits(['delete','start-record'])
const recent=computed(()=>recentRecords(props.records));const days=computed(()=>lastSevenDays());const values=computed(()=>days.value.map(day=>{const list=recent.value.filter(item=>dayKey(item.createdAt)===dayKey(day)).map(item=>item.intensity);return list.length?+(list.reduce((a,b)=>a+b,0)/list.length).toFixed(1):null}));const labels=computed(()=>days.value.map(day=>`${day.getMonth()+1}/${day.getDate()}`));const average=computed(()=>recent.value.length?(recent.value.reduce((sum,item)=>sum+item.intensity,0)/recent.value.length).toFixed(1):'—')
const emotion=computed(()=>mostCommon(recent.value,'emotionTags'));const trigger=computed(()=>mostCommon(recent.value,'triggerTags'));const observation=computed(()=>weeklyObservation(recent.value))
</script>
<template><section class="trends-view"><div class="section-intro"><p class="eyebrow">最近 7 天</p><h1>看见情绪的<span>流动</span></h1><p>趋势不是评判，它只是帮你更了解自己。</p></div>
  <template v-if="recent.length"><div class="stat-grid four"><div class="stat-card"><span>平均情绪强度</span><strong>{{ average }}<small>/10</small></strong><p>最近七天</p></div><div class="stat-card"><span>记录次数</span><strong>{{ recent.length }}<small>次</small></strong><p>每一次都算数</p></div><div class="stat-card"><span>最常见情绪</span><strong class="text-stat">{{ emotion }}</strong><p>近期更常出现</p></div><div class="stat-card"><span>最常见触发</span><strong class="text-stat">{{ trigger }}</strong><p>值得多留意</p></div></div><section class="card chart-card"><div class="chart-heading"><div><p class="eyebrow">情绪强度</p><h2>一周趋势</h2></div><div class="legend"><i></i>我的记录</div></div><TrendChart :days="labels" :values="values"/></section><section class="weekly-insight"><div class="insight-symbol">✦</div><div><p class="eyebrow">本周观察</p><h2>这些记录正在告诉你</h2><p>{{ observation }}</p></div></section></template>
  <div v-else class="empty-state trend-empty"><span>⌁</span><h2>还没有足够的记录</h2><p>从今天开始记录一次情绪，之后这里会慢慢出现属于你的变化轨迹。</p><button class="primary-button" type="button" @click="emit('start-record')">记录此刻</button></div>
  <HistoryList :records="records" @delete="emit('delete',$event)"/>
</section></template>
