const RECORDS_KEY='moodflow-records-v2',LEGACY_KEY='moodflow-records-v1',DRAFT_KEY='moodflow-care-writing-v1',WRITINGS_KEY='moodflow-writing-records-v2',CUSTOM_KEY='moodflow-custom-tags-v1',CARE_KEY='moodflow-care-completions-v1'
function parse(value,fallback){try{return JSON.parse(value)??fallback}catch{return fallback}}
function id(prefix='item'){return`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function normalizeActivity(item={}){return{id:item.id||id('care'),actionId:item.actionId||'unknown',actionName:item.actionName||'自我关怀',startedAt:item.startedAt||'',completedAt:item.completedAt||new Date().toISOString(),...(item.writingPrompt?{writingPrompt:item.writingPrompt}:{}),...(item.writingAnswer?{writingAnswer:item.writingAnswer}:{})}}
export function normalizeRecord(record={}){return{id:record.id||id('mood'),createdAt:record.createdAt||record.date||new Date().toISOString(),updatedAt:record.updatedAt||record.createdAt||record.date||new Date().toISOString(),mood:record.mood||'一般',intensity:Number(record.intensity)||5,emotionTags:Array.isArray(record.emotionTags)?record.emotionTags:[],triggerTags:Array.isArray(record.triggerTags)?record.triggerTags:record.trigger?[record.trigger]:[],need:record.need||'',positiveChoice:record.positiveChoice||'',note:record.note||'',insightSummary:record.insightSummary||'',primaryAction:record.primaryAction||'',legacyRecommendedAction:record.legacyRecommendedAction||record.primaryAction||'',recommendedActionIds:Array.isArray(record.recommendedActionIds)?record.recommendedActionIds:[],selectedActionId:record.selectedActionId||null,selectedActionLabel:record.selectedActionLabel||null,selectedActionAt:record.selectedActionAt||null,completedActionIds:Array.isArray(record.completedActionIds)?record.completedActionIds:[],writingRecordIds:Array.isArray(record.writingRecordIds)?record.writingRecordIds:[],careActivities:Array.isArray(record.careActivities)?record.careActivities.map(normalizeActivity):[],customTags:record.customTags||{emotion:[],trigger:[],need:[]}}}
export function loadRecords(){const current=parse(localStorage.getItem(RECORDS_KEY),[]);if(Array.isArray(current)&&current.length)return current.map(normalizeRecord);const legacy=parse(localStorage.getItem(LEGACY_KEY),[]);if(Array.isArray(legacy)&&legacy.length){const migrated=legacy.map(normalizeRecord);localStorage.setItem(RECORDS_KEY,JSON.stringify(migrated));return migrated}return[]}
export function upsertRecord(record){const records=loadRecords(),index=records.findIndex(x=>x.id===record.id),next=normalizeRecord({...record,updatedAt:new Date().toISOString()});if(index>=0)records[index]=next;else records.unshift(next);localStorage.setItem(RECORDS_KEY,JSON.stringify(records));return records}
export const saveRecord=upsertRecord
export function updateRecordAction(recordId,action){const records=loadRecords(),record=records.find(x=>x.id===recordId);return record?upsertRecord({...record,selectedActionId:action.id,selectedActionLabel:action.label,selectedActionAt:new Date().toISOString()}):records}
function normalizeWriting(item={}){return{id:item.id||id('writing'),createdAt:item.createdAt||item.completedAt||new Date().toISOString(),completedAt:item.completedAt||item.createdAt||new Date().toISOString(),prompt:item.prompt||item.writingPrompt||'',answer:item.answer||item.writingAnswer||'',sourceType:item.sourceType==='emotion'&&item.sourceRecordId?'emotion':'standalone',sourceRecordId:item.sourceRecordId||null,moodSnapshot:item.moodSnapshot||null,emotionTagsSnapshot:Array.isArray(item.emotionTagsSnapshot)?item.emotionTagsSnapshot:[],triggerTagsSnapshot:Array.isArray(item.triggerTagsSnapshot)?item.triggerTagsSnapshot:[]}}
function migrateLegacyWritings(){const existing=parse(localStorage.getItem(WRITINGS_KEY),null);if(Array.isArray(existing))return existing.map(normalizeWriting);const records=loadRecords(),completions=parse(localStorage.getItem(CARE_KEY),[]),seen=new Set(),writings=[];for(const record of records){for(const activity of record.careActivities||[]){if(activity.writingPrompt&&activity.writingAnswer){const wid=`legacy-${activity.id}`;if(!seen.has(wid)){seen.add(wid);writings.push(normalizeWriting({id:wid,createdAt:activity.completedAt,prompt:activity.writingPrompt,answer:activity.writingAnswer,sourceType:'emotion',sourceRecordId:record.id,moodSnapshot:record.mood,emotionTagsSnapshot:record.emotionTags,triggerTagsSnapshot:record.triggerTags}));record.writingRecordIds=[...new Set([...(record.writingRecordIds||[]),wid])]}}}record.careActivities=(record.careActivities||[]).map(normalizeActivity)}for(const item of completions){if(item.writingPrompt&&item.writingAnswer){const wid=`legacy-${item.id}`;if(!seen.has(wid)){seen.add(wid);const source=records.find(x=>x.id===item.sourceRecordId);writings.push(normalizeWriting({id:wid,createdAt:item.completedAt,prompt:item.writingPrompt,answer:item.writingAnswer,sourceType:source?'emotion':'standalone',sourceRecordId:source?.id||null,moodSnapshot:source?.mood,emotionTagsSnapshot:source?.emotionTags,triggerTagsSnapshot:source?.triggerTags}));if(source)source.writingRecordIds=[...new Set([...(source.writingRecordIds||[]),wid])]}}}localStorage.setItem(WRITINGS_KEY,JSON.stringify(writings));localStorage.setItem(RECORDS_KEY,JSON.stringify(records));return writings}
export function loadWritingRecords(){return migrateLegacyWritings().sort((a,b)=>new Date(b.completedAt)-new Date(a.completedAt))}
export function saveWritingRecord(data){const source=data.sourceRecordId?loadRecords().find(x=>x.id===data.sourceRecordId):null,record=normalizeWriting({...data,id:id('writing'),createdAt:new Date().toISOString(),completedAt:new Date().toISOString(),sourceType:source?'emotion':'standalone',sourceRecordId:source?.id||null,moodSnapshot:source?.mood||null,emotionTagsSnapshot:source?.emotionTags||[],triggerTagsSnapshot:source?.triggerTags||[]}),next=[record,...loadWritingRecords()];localStorage.setItem(WRITINGS_KEY,JSON.stringify(next));if(source)upsertRecord({...source,writingRecordIds:[...new Set([...(source.writingRecordIds||[]),record.id])]});return{record,records:loadRecords(),writings:next}}
export function deleteWritingRecord(writingId){const writings=loadWritingRecords().filter(x=>x.id!==writingId);localStorage.setItem(WRITINGS_KEY,JSON.stringify(writings));const records=loadRecords().map(record=>({...record,writingRecordIds:(record.writingRecordIds||[]).filter(x=>x!==writingId)}));localStorage.setItem(RECORDS_KEY,JSON.stringify(records));return{records:records.map(normalizeRecord),writings}}
export function deleteRecord(recordId){const next=loadRecords().filter(x=>x.id!==recordId);localStorage.setItem(RECORDS_KEY,JSON.stringify(next));const writings=loadWritingRecords().map(w=>w.sourceRecordId===recordId?{...w,sourceType:'standalone',sourceRecordId:null}:w);localStorage.setItem(WRITINGS_KEY,JSON.stringify(writings));return next}
export function loadCustomTags(){const value=parse(localStorage.getItem(CUSTOM_KEY),{});return{emotion:Array.isArray(value.emotion)?value.emotion:[],trigger:Array.isArray(value.trigger)?value.trigger:[],need:Array.isArray(value.need)?value.need:[]}}
export function saveCustomTag(type,label){const tags=loadCustomTags();if(!tags[type]||tags[type].includes(label))return tags;tags[type]=[...tags[type],label];localStorage.setItem(CUSTOM_KEY,JSON.stringify(tags));return tags}
export function deleteCustomTag(type,label){const tags=loadCustomTags();tags[type]=(tags[type]||[]).filter(x=>x!==label);localStorage.setItem(CUSTOM_KEY,JSON.stringify(tags));return tags}
export function loadCareCompletions(){const values=parse(localStorage.getItem(CARE_KEY),[]);return Array.isArray(values)?values.map(item=>({...normalizeActivity(item),sourceRecordId:item.sourceRecordId||''})):[]}
export function saveCareCompletion(completion){const activity=normalizeActivity(completion),entry={...activity,sourceRecordId:completion.sourceRecordId||''},next=[entry,...loadCareCompletions()];localStorage.setItem(CARE_KEY,JSON.stringify(next));if(entry.sourceRecordId){const record=loadRecords().find(x=>x.id===entry.sourceRecordId);if(record)upsertRecord({...record,completedActionIds:[...new Set([...(record.completedActionIds||[]),entry.actionId])],careActivities:[...(record.careActivities||[]),activity]})}return next}
export function loadWriting(){return localStorage.getItem(DRAFT_KEY)||''}export function saveWriting(value){localStorage.setItem(DRAFT_KEY,value)}
