export const MOOD_SCORES={很难受:2,低落:4,一般:6,不错:8,很好:10}
export function startOfDay(value=new Date()){const date=new Date(value);date.setHours(0,0,0,0);return date}
export function dayKey(value){const date=new Date(value);return`${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`}
export function daysForRange(count,now=new Date()){const end=startOfDay(now);return Array.from({length:count},(_,index)=>{const date=new Date(end);date.setDate(end.getDate()-(count-1-index));return date})}
export function recordsInRange(records,count,now=new Date()){const start=daysForRange(count,now)[0];return records.filter(item=>{const date=new Date(item.createdAt);return !Number.isNaN(date.getTime())&&date>=start&&date<=now})}
export function completionsInRange(items,count,now=new Date()){const start=daysForRange(count,now)[0];return items.filter(item=>{const date=new Date(item.completedAt);return !Number.isNaN(date.getTime())&&date>=start&&date<=now})}
export function countValues(values){const counts=values.filter(Boolean).reduce((map,value)=>((map[value]=(map[value]||0)+1),map),{});return Object.entries(counts).sort((a,b)=>b[1]-a[1])}
export function mostCommon(records,field){return countValues(records.flatMap(item=>Array.isArray(item[field])?item[field]:item[field]?[item[field]]:[]))[0]?.[0]||'还在积累'}
export function moodDistribution(records){const order=['很好','不错','一般','低落','很难受'],total=records.length||1;return order.map(mood=>{const count=records.filter(item=>item.mood===mood).length;return{mood,count,percent:Math.round(count/total*100)}}).filter(item=>item.count)}
export function positiveFactors(records){return countValues(records.filter(item=>['很好','不错'].includes(item.mood)).flatMap(item=>item.triggerTags||[])).slice(0,3).map(([label])=>label)}
export function moodScore(record){if(MOOD_SCORES[record?.mood])return MOOD_SCORES[record.mood];const fallback=Number(record?.intensity);return Number.isFinite(fallback)?Math.min(10,Math.max(0,fallback)):null}
function pad(value){return String(value).padStart(2,'0')}
function timeLabel(value){const date=new Date(value);return`${pad(date.getHours())}:${pad(date.getMinutes())}`}
function dateLabel(date){return`${date.getMonth()+1}月${date.getDate()}日`}
function shortDate(date){return`${date.getMonth()+1}/${date.getDate()}`}
function weekday(date){return`周${'日一二三四五六'[date.getDay()]}`}
function average(values){return values.length?+(values.reduce((sum,value)=>sum+value,0)/values.length).toFixed(1):null}
function aggregate(list,label,detailLabel){const scores=list.map(moodScore).filter(Number.isFinite);return{label,detailLabel,value:average(scores),count:scores.length,min:scores.length?Math.min(...scores):null,max:scores.length?Math.max(...scores):null}}
function validRecords(records){return records.filter(item=>Number.isFinite(moodScore(item))&&!Number.isNaN(new Date(item.createdAt).getTime()))}
function todayPoints(records,now){const key=dayKey(now);return validRecords(records).filter(item=>dayKey(item.createdAt)===key).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt)).map(item=>aggregate([item],timeLabel(item.createdAt),`${dateLabel(new Date(item.createdAt))} ${timeLabel(item.createdAt)}`))}
function dailyPoints(records,count,now){const valid=validRecords(records);return daysForRange(count,now).map((date,index)=>{const list=valid.filter(item=>dayKey(item.createdAt)===dayKey(date)),label=count===7?`${weekday(date)}\n${shortDate(date)}`:shortDate(date);return{...aggregate(list,label,dateLabel(date)),axisIndex:index}})}
function mondayOf(value){const date=startOfDay(value),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);return date}
function weeklyPoints(records,now){const start=startOfDay(now);start.setDate(start.getDate()-89);const firstWeek=mondayOf(start),lastWeek=mondayOf(now),weeks=[];for(let cursor=new Date(firstWeek);cursor<=lastWeek;cursor.setDate(cursor.getDate()+7))weeks.push(new Date(cursor));const valid=validRecords(records).filter(item=>new Date(item.createdAt)>=start&&new Date(item.createdAt)<=now);return weeks.map(week=>{const end=new Date(week);end.setDate(end.getDate()+6);const list=valid.filter(item=>mondayOf(item.createdAt).getTime()===week.getTime());return aggregate(list,`${week.getMonth()+1}/${week.getDate()}`,`${dateLabel(week)}－${dateLabel(end)}`)})}
function movingAverage(points,windowSize=7){return points.map((_,index)=>{const values=points.slice(Math.max(0,index-windowSize+1),index+1).map(point=>point.value).filter(Number.isFinite);return values.length?average(values):null})}
function pointStats(points){const recorded=points.filter(point=>Number.isFinite(point.value)),count=recorded.reduce((sum,point)=>sum+point.count,0),weightedTotal=recorded.reduce((sum,point)=>sum+point.value*point.count,0),lows=recorded.map(point=>point.min),highs=recorded.map(point=>point.max);return{recorded,average:count?+(weightedTotal/count).toFixed(1):null,min:lows.length?Math.min(...lows):null,max:highs.length?Math.max(...highs):null,count}}
function observation(scale,points){const{recorded,min,max}=pointStats(points);if(recorded.length<2)return scale==='today'?'今天再记录几次后，可以看到一天里的情绪变化。':'再记录几次后，这里会慢慢出现更清楚的变化。';const range=max-min;if(scale==='today'){const half=Math.ceil(recorded.length/2),early=recorded.slice(0,half).map(item=>item.value),late=recorded.slice(half).map(item=>item.value);if(late.length){const direction=average(late)-average(early);if(direction>=1)return'今天后半段的状态比前半段有所回升。';if(direction<=-1)return'今天后半段的状态比前半段低了一些。'}return range<=2?'今天的状态变化比较平稳。':'今天不同时间的感受有一些变化。'}if(scale==='7d'){if(range<=2)return'最近 7 天整体比较平稳。';const low=recorded.reduce((result,item)=>item.value<result.value?item:result);return`最近 7 天有一些起伏，${low.detailLabel}是相对低点。`}const third=Math.max(1,Math.floor(recorded.length/3)),early=average(recorded.slice(0,third).map(item=>item.value)),late=average(recorded.slice(-third).map(item=>item.value)),delta=late-early;if(delta>=.8)return scale==='30d'?'这个月的整体状态比月初有所回升。':'过去三个月的整体状态呈现缓慢回升。';if(delta<=-.8)return scale==='30d'?'这个月后段的整体状态比月初低了一些。':'过去三个月后段的整体状态比前段低了一些。';return scale==='30d'?'这个月的整体变化比较平稳。':'过去三个月的整体变化比较平稳。'}
export function buildTrend(records,scale='7d',now=new Date()){const points=scale==='today'?todayPoints(records,now):scale==='7d'?dailyPoints(records,7,now):scale==='30d'?dailyPoints(records,30,now):weeklyPoints(records,now),stats=pointStats(points);return{points,stats,observation:observation(scale,points),movingAverage:scale==='30d'?movingAverage(points):[],hasData:stats.count>0}}
export function volatility(records){const values=validRecords(records).map(moodScore);if(values.length<2)return'再多记录几次，就能看见情绪变化的幅度。';return Math.max(...values)-Math.min(...values)<=2?'这段时间的整体状态比较平稳。':'这段时间的状态有一些起伏。'}
export function weeklyObservation(records){return observation('7d',dailyPoints(records,7,new Date()))}
